#!/bin/sh
#searches and plays the first results in youtube
query=$(printf '%s' "$*" | tr ' ' '+')
mpv "https://youtube.com/$(curl -s "https://vid.puffyan.us/search?q=$query" | grep -Eo "watch\?v=.{11}" | head -n 1)"
